# Generated by Django 3.1 on 2020-08-23 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20200823_1158'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewViewSet',
            new_name='New',
        ),
    ]
